name: ci
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
      - development

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: npm CI
        run: npm ci

      - name: npm Check
        run: npm run check

      - name: npm Test
        run: npm run test

      - name: npm Build
        run: npm run build
